#!/usr/bin/env python3
"""
Generate CHANGELOG.md from the dated pricing patches.

Why this exists
---------------
The single most linkable artifact this site can have is a *record of price
movement*. Every other price tracker publishes a snapshot; none of them publish
"this provider cut input 20% on this date". Bloggers, newsletter writers and
journalists cite price *changes*, not price *tables*, because a change is a
fact with a date and a source and a table is just a number.

So the changelog is generated, not written by hand: it can never disagree with
data/model-prices.json or with the patch files that justify it.

Reads every pricing-patch-*.json in the project root and writes CHANGELOG.md.

Usage:  python gen_changelog.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "repo" / "CHANGELOG.md"

# Grouping so the changelog reads as a story, not a dump.
CORRECTION_KIND = "correction"
ADDITION_KIND = "addition"
FLAG_KIND = "unverified"


def money(v):
    if v is None:
        return "—"
    v = float(v)
    if v == 0:
        return "Free"
    return f"${v:,.10g}"


def pct(old, new):
    if not old:
        return None
    return (new - old) / old * 100.0


def main():
    patches = sorted(ROOT.glob("pricing-patch-*.json"))
    if not patches:
        raise SystemExit("no pricing-patch-*.json found")

    baseline = json.loads(
        (ROOT / "_baseline" / "data" / "model-prices.json").read_text(encoding="utf-8")
    )
    base_by_id = {m["id"]: m for m in baseline["models"]}

    sections = []
    total_c = total_a = total_f = 0

    for pf in patches:
        p = json.loads(pf.read_text(encoding="utf-8"))["_patch"]

        lines = [f"## {p['date']}", ""]

        prev = p.get("previousLastVerified")
        if prev:
            lines.append(
                f"Prices re-verified against provider pages. Previous snapshot: `{prev}`."
            )
            lines.append("")

        # ---------------- corrections
        corr = p.get("corrections", [])
        if corr:
            total_c += len(corr)
            lines += [
                "### Corrected",
                "",
                "Figures that were published wrong and are now fixed. These are the ones that",
                "mattered: an understated context window sends people to the wrong model.",
                "",
                "| Model | Field | Was | Now | Why |",
                "|---|---|---|---|---|",
            ]
            for c in corr:
                lines.append(
                    f"| `{c['id']}` | `{c['field']}` | `{c['from']}` | `{c['to']}` | {c['why']} |"
                )
            lines.append("")
            for c in corr:
                lines.append(f"**`{c['id']}` source**")
                for s in c.get("sources", []):
                    lines.append(f"- {s}")
                lines.append("")

        # ---------------- additions
        adds = p.get("additions", [])
        if adds:
            total_a += len(adds)
            lines += [
                "### Added",
                "",
                "| Model | Provider | Input / 1M | Output / 1M | Cached / 1M | Context |",
                "|---|---|---|---|---|---|",
            ]
            for a in adds:
                lines.append(
                    f"| {a['label']} | {a['provider']} | {money(a['priceInputPer1M'])} | "
                    f"{money(a['priceOutputPer1M'])} | "
                    f"{money(a.get('priceCachedInputPer1M'))} | {a.get('contextWindow', '—')} |"
                )
            lines.append("")
            for a in adds:
                lines.append(f"**{a['label']}**")
                if a.get("note"):
                    lines.append(f"- {a['note']}")
                for s in a.get("sources", []):
                    lines.append(f"- source: {s}")
                lines.append("")

        # ---------------- flagged
        flags = p.get("flagged_not_changed", [])
        if flags:
            total_f += len(flags)
            lines += [
                "### Published but unverified",
                "",
                "Models or fields we could not confirm from a source we trust. Listed here",
                "rather than guessed at — a wrong rate is worse than a missing row.",
                "",
                "| Model | Status | Why not filled in |",
                "|---|---|---|",
            ]
            for f in flags:
                lines.append(f"| `{f['id']}` | {f['status']} | {f['why']} |")
            lines.append("")

        sections.append("\n".join(lines))

    head = f"""# Pricing changelog

Machine-generated by `gen_changelog.py` from the patch files in this repo. Do not
edit by hand — regenerate instead:

```bash
python gen_changelog.py
```

Each entry lists the source URL for every figure. `_meta.lastVerified` in
[`data/model-prices.json`](data/model-prices.json) is the authoritative date; it
moves only when someone has actually re-checked a provider page.

**Why this file exists.** Every other price tracker publishes a snapshot. None of
them publish *movement*. If you are writing about how LLM prices are changing,
this is the citable record:

> TokenCalc, "LLM Pricing Changelog", tokenestimate.com, {patches[-1].stem.replace('pricing-patch-', '')}

**Totals so far:** {total_a} models added, {total_c} corrections, {total_f} entries flagged unverified.

---

"""

    body = "\n".join(sections)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(head + body, encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {total_a} additions, {total_c} corrections, {total_f} flagged")
    print(f"  {len(body.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())